### ISSUE TITLE
Rule CL-01

### ISSUE THREAD

**Issue by kpetersdms** [itplr-kosit/validationtool#5]
I think the implmentation of rule CL01 for the document type code ist wrong. 
The Test test="((not(contains(normalize-space(.), ' 80 81 82 83 84 130 202 203 204 211 261 262 295 296 308 325 326 380 381 383 384 385 386 387 388 389 390 393 394 395 396 420 456 457 458 527 575 623 633 751 780 935 ')) and contains('  ', concat(' ', normalize-space(.), ' '))))" does not allow for example the value 380 (commerial invoice).
The test should be test="((not(contains(normalize-space(.), ' ')) and contains(' 80 81 82 83 84 130 202 203 204 211 261 262 295 296 308 325 326 380 381 383 384 385 386 387 388 389 390 393 394 395 396 420 456 457 458 527 575 623 633 751 780 935 ', concat(' ', normalize-space(.), ' '))))" (the same structure as for e,g, CL-03, CL-04, ...

**Comment by fbuettner-hb** [comment]
The XSLT file is generated from the Schematron file in the CEN TC 434 validation repository (https://github.com/CenPC434/validation). 

Please open a ticket there.

If new Schematron files are released there, we will provide a new configuration (with updated XSLT files).

**Comment by fbuettner-hb** [comment]
I just noticed https://github.com/CenPC434/validation/issues/43 - the Schematron files have already been fixed. The XSLT files in the XRechnung configuration already contain that fix. We will release a new release this week.

**Comment by fbuettner-hb** [comment]
Released new configuration.
